/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";
import { useRouter } from "next/router";
import Stepper from "@/components/Stepper";
import type { Order } from "@/types/order";
import { Customer } from "@/types/customers";
import Spline from "@splinetool/react-spline";
import ClaimFree from "@/components/ClaimFreeBoba";
import ClaimFreeBoba from "@/components/ClaimFreeBoba";

export default function Me() {
  // get slug from the URL

  const { slug } = useRouter().query;

  const customer = api.customer.get_by_school_ID.useQuery({
    sid: slug as string,
  });

  const numberOfFreeBoba = Math.floor(
    (customer.data?.orders as Order[])?.length / 5,
  );

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-12 flex min-h-screen flex-col items-center">
        {/* <div className="flex w-full justify-end py-5">
          <div className="p-4">
            {numberOfFreeBoba} boba gratuits
            <button className="ml-4 rounded-full bg-green-500 px-4 py-2 font-bold text-white hover:bg-green-700">
              Réclamer
            </button>
          </div>
        </div> */}
        <h1 className="text-4xl">
          Salut, {(customer.data?.customer as Customer)?.given_name}{" "}
        </h1>
        <h3>Voici ton progrès</h3>
        <Stepper
          orders={
            (customer.data?.orders as Order[])?.length - 5 * numberOfFreeBoba
          }
        />
        <ClaimFreeBoba customer={customer} />
      </main>
    </>
  );
}
