/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";
import { useRouter } from "next/router";
import Stepper from "@/components/Stepper";
import type { Order } from "@/types/order";
import { Customer } from "@/types/customers";
import Spline from "@splinetool/react-spline";

export default function Home() {
  // get slug from the URL

  const { slug } = useRouter().query;

  const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const customer = api.customer.get_by_school_ID.useQuery({
    sid: slug as string,
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center ">
        <div className="flex w-full justify-end py-5">
          <div className="p-4">
            {Math.floor((customer.data?.orders as Order[])?.length / 5)} boba
            gratuits
            <button className="ml-4 rounded-full bg-green-500 px-4 py-2 font-bold text-white hover:bg-green-700">
              Réclamer
            </button>
          </div>
        </div>
        <h1 className="text-4xl">
          Salut, {(customer.data?.customer as Customer)?.given_name}{" "}
        </h1>
        <h3>Voici ton progrès</h3>
        <Stepper
          orders={
            (customer.data?.orders as Order[])?.length -
            Math.floor((customer.data?.orders as Order[])?.length / 5)
          }
        />
        <div className="mt-32">
          <h1 className="mb-8 text-2xl">Pas de boba à réclamer :(</h1>
          <Spline
            style={{ height: "500px" }}
            scene="https://prod.spline.design/Jh1UFzqccFhPMyBJ/scene.splinecode"
          />
        </div>
      </main>
    </>
  );
}
